# Trained with RTX 3090 (24 GB). It takes 22 minutes per epoch.
encoder: conformer
encoder_conf:
    output_size: 1024
    attention_heads: 8
    linear_units: 4096
    num_blocks: 8
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    normalize_before: true
    macaron_style: true
    pos_enc_layer_type: "rel_pos"
    rel_pos_type: "latest"
    selfattention_layer_type: "rel_selfattn"
    activation_type: "swish"
    use_cnn_module: true
    cnn_module_kernel: 31

postencoder: hugging_face_transformers
postencoder_conf:
    model_name_or_path: "akreal/mbart-large-50-finetuned-portmedia-dom"
    length_adaptor_n_layers: 1
    lang_token_id: 250008

decoder: hugging_face_transformers
decoder_conf:
    model_name_or_path: "akreal/mbart-large-50-finetuned-portmedia-dom"

batch_type: length
batch_bins: 300000
optim: adam
optim_conf:
    lr: 0.00003
scheduler: warmuplr     # pytorch v1.1.0+ required
scheduler_conf:
    warmup_steps: 15000
max_epoch: 100

freeze_param: [
    "frontend.upstream"
]

frontend_conf:
    n_fft: 512
    hop_length: 256

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: wav2vec2_url  # Note: If the upstream is changed, please change the input_size in the preencoder.
        upstream_ckpt: https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr2_300m.pt
    download_dir: /fs/scratch/users/denisopl/hub
    multilayer_feature: True

preencoder: linear
preencoder_conf:
    input_size: 1024  # Note: If the upstream is changed, please change this value accordingly.
    output_size: 80

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false   # Note: "False" means during collect stats (stage 10), generating dummy stats files rather than extract_feats by forward frontend.
    # BART dictionary customizations
    ignore_id: 1
    sym_blank: "<pad>"
    sym_sos: "<s>"
    sym_eos: "</s>"
    lang_token_id: 250008

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
